export const CHANGE_SEARCH_FIELD ='CHANGE_SEARCH_FIELD';
export const LOGIN_FAILED='LOGIN_FAILED';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const MODIFY_USER='MODIFY_USER';
export const CLEAR_ERRORS='CLEAR_ERRORS';